### ISSUE TITLE
Pause automatisch subtrahieren 

### ISSUE THREAD

**Issue by rathjevt** [MathisBurger/wtm#38]
In den Mandanteneinstellungen soll man festlegen können, das für einen Mandanten automatisch eine Mittagspause abgezogen wird.
Beispiel:
Max Mustermann Arbeitet von 07:00 Uhr bis 16:30 Uhr und hat zwischen 13:00 Uhr und 14:00 Uhr Mittagspause. Da Max Mustermann im Kundendienst arbeitet kann er sich nicht für die Pause ausstempeln. Wenn er sich um 16:30 ausloggt soll er also 8,5 Stunden und nicht 9,5 Stunden gearbeitet haben. Die Stunde Pause wird aber nur dann abgezogen, wenn er sich vor Pausenbeginn nicht ausstempelt(Bsp.: Er Arbeitet nur bis 12 Uhr hat er natürlich 5 Stunden und nicht nur 4 Stunden gearbeitet)

**Comment by MathisBurger** [comment]
Sollte gelöst sein.
